### PR TITLE
Initial Frontend Changes

### PR DESCRIPTION
**Pull request by michaeleliot**
I started working on the application frontend in react. Still lots to be done. Below is a discussion of what still needs to be done. I mainly did work in the splash page which is from the design doc. I used material ui, which is google's frontend standards. I also made some changes too the app.js to make routing easier. There is definitely some spaghetti code in here, specifically with some of the constraints I set up. If there are any questions lmk. Lastly, there was some lingering code from the toy app we did. It did not compile, but seemed handy. So, I moved it into code_for_later.

Current Look:
screen shot 2018-11-06 at 4 54 07 pm

**BUGS**
- Currently the dropdown for ether opens the dropdown for energy

**Design Issues**
- The font sucks, but typography won't let me change it. Maybe worth switching off typography.
- The slider's design should be changed. There are only two sliders I could find, I will try the other if I have time. 
- Various sizing constraints need to be redone. Specifically, that of the continue button
- The background fade isn't quite right.
- We need to add icons to things

**Features**
- Implementing login page, and connecting buttons to that login page
- Adding in the actual ether/energy conversion + being able to make those transactions

### CODE REVIEW

**Comment by jfcong** [comment]
We might have to discuss this, but I think any type of user should sign up with their ethereum account address with metamask. So when a user clicks login, we can use their address to call the smart contract to verify the type of the user and direct them to the appropriate pages. I am just not sure about the signing up part. Perhaps when a user clicks sign up, they will fill out a form like usual, and their address will also be recorded on the form, and the form is sent to a verifying party, be that the governement, the utility company, or us, then we "approve" them and manually add them to the mapping in the smart contract.

**Comment by michaeleliot** [comment]
Added more boiler plate for user account and login. We def should discuss exactly how we would want an individual to sign in. User sessions is vv important to this project.
screen shot 2018-11-11 at 1 08 04 am
screen shot 2018-11-11 at 1 08 13 am

 

BUGS

- The dropdown currently does not overlap well with the screen, but they are now separated

Design Issues

- The spacing on the user page needs to be better
- The fields themselves could be better designed

Features

- Adding in a login system
- Making a clearer separation of accounts

**Comment by jfcong** [comment]
So what I was thinking/trying to say was that we might not need a login page. A user would just login on metamask -> click log in button -> that will send a verification request to our smart contract, and it will return the type of the user (user/UC/FFG) as a number -> redirect user directly to their respecting dashboard. Also, found a small bug on the dashboard page: you can enter and delete texts in the text field. But great progress Michael!!!

**Comment by michaeleliot** [comment]
Interesting. I will take a look at metamask login and get back to you

**Pull request merged**
